name: Hello ISIS3710!

on:
  push:
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: ubuntu-18.04
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Print date
        run: echo $TAG_NAME
        env:
          TAG_NAME: Fecha-${{ steps.date.outputs.date }}
