name: Pipeline React

on:
  push:
    branches:
      - master

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm clean
        run: npm cache clean --force
      - name: npm install 
        run: rm -rf node_modules && npm install  
      - name: Build
        run: npm run build